sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fgigante/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fgigante/react-test npm test

after_success:
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t aidfgdocker/multi-client ./client
  - docker build -t aidfgdocker/multi-nginx ./nginx
  - docker build -t aidfgdocker/multi-server ./server
  - docker build -t aidfgdocker/multi-worker ./worker

  # Take those images and push them to docker hub
  - docker push aidfgdocker/multi-client
  - docker push aidfgdocker/multi-nginx
  - docker push aidfgdocker/multi-server
  - docker push aidfgdocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-011528270992'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
